[alias]
lint = [
     "clippy",
     "--",
     "-D",
     "clippy::pedantic",
     "-D",
     "clippy::cargo",
     "-A",
     "clippy::option_if_let_else",
     "-A",
     "clippy::cast_possible_truncation",
     "-A",
     "clippy::cast_possible_wrap",
     "-A",
     "clippy::cast_sign_loss"
]
